apiVersion: anynines.com/v1
kind: Restore
metadata:
  name: example-a9s-search
spec:
  crossplane:
    compositionRef:
      name: a9s-restore
    backupRef: example-a9s-search
    serviceInstanceType: search
