apiVersion: anynines.com/v1
kind: Restore
metadata:
  name: example-a9s-search
spec:
  backupRef: example-a9s-search
  serviceInstanceType: search
  crossplane:
    compositionRef:
      name: a9s-restore
