apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: a9s-postgresql
spec:
  compositeTypeRef:
    apiVersion: anynines.com/v1
    kind: XPostgresqlInstance
  mode: Pipeline
  pipeline:
    - step: patch-and-transform
      functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - name: a9s-postgresql
            base:
              apiVersion: dataservices.anynines.com/v1
              kind: ServiceInstance
              spec:
                forProvider:
                  # acceptsIncomplete indicates if the service broker can fulfill a
                  # request asynchronously. Since the anynines-provider controller
                  # reconciles the resources asynchronously, if 'acceptsIncomplete' is
                  # not specified by the user, it will default to 'true'.
                  acceptsIncomplete: true
                  # OrganizationGUID is the platform GUID for the organization under
                  # which the service is to be provisioned. This value is specific to
                  # Cloud Foundry.
                  organizationGuid: a1d46b5c-b639-4f43-85c7-e9a0e5f01f75
                  # SpaceGUID is the identifier for the project space within the
                  # platform organization. This value is specific to Cloud Foundry.
                  spaceGuid: 1bf71cf3-9017-4846-bffc-b9b31872bfaf
                providerConfigRef:
                  name: postgresql-service-broker
            patches:
              - fromFieldPath: metadata.labels[crossplane.io/claim-namespace]
                toFieldPath: metadata.labels[crossplane.io/claim-namespace]
              - fromFieldPath: metadata.labels[crossplane.io/claim-name]
                toFieldPath: metadata.labels[crossplane.io/claim-name]
              - fromFieldPath: spec.service
                toFieldPath: spec.forProvider.serviceName
              - fromFieldPath: spec.plan
                toFieldPath: spec.forProvider.planName
              - fromFieldPath: spec.acceptsIncomplete
                toFieldPath: spec.forProvider.acceptsIncomplete

              - fromFieldPath: spec.parameters.dataChecksums
                toFieldPath: spec.forProvider.parameters.data_checksums
              - fromFieldPath: spec.parameters.maxConnections
                toFieldPath: spec.forProvider.parameters.max_connections
              - fromFieldPath: spec.parameters.effectiveCacheSize
                toFieldPath: spec.forProvider.parameters.effective_cache_size
              - fromFieldPath: spec.parameters.workMem
                toFieldPath: spec.forProvider.parameters.work_mem
              - fromFieldPath: spec.parameters.maintenanceWorkMem
                toFieldPath: spec.forProvider.parameters.maintenance_work_mem
              - fromFieldPath: spec.parameters.tempFileLimit
                toFieldPath: spec.forProvider.parameters.temp_file_Limit
              - fromFieldPath: spec.parameters.trackIoTiming
                toFieldPath: spec.forProvider.parameters.track_io_timing
              - fromFieldPath: spec.parameters.archiveTimeout
                toFieldPath: spec.forProvider.parameters.archive_timeout
              - fromFieldPath: spec.parameters.statementTimeout
                toFieldPath: spec.forProvider.parameters.statement_timeout
              - fromFieldPath: spec.parameters.idleInTransactionSessionTimeout
                toFieldPath: spec.forProvider.parameters.idle_in_transaction_session_timeout
              - fromFieldPath: spec.parameters.rolePrivileges
                toFieldPath: spec.forProvider.parameters.role_privileges
              - fromFieldPath: spec.parameters.walLevelLogical
                toFieldPath: spec.forProvider.parameters.wal_level_logical
              - fromFieldPath: spec.parameters.walWriterDelay
                toFieldPath: spec.forProvider.parameters.wal_writer_delay
              - fromFieldPath: spec.parameters.maxReplicationSlots
                toFieldPath: spec.forProvider.parameters.max_replication_slots
              - fromFieldPath: spec.parameters.maxWalSenders
                toFieldPath: spec.forProvider.parameters.max_wal_senders
              - fromFieldPath: spec.parameters.synchronousCommit
                toFieldPath: spec.forProvider.parameters.synchronous_commit
              - fromFieldPath: spec.parameters.clientMinMessages
                toFieldPath: spec.forProvider.parameters.client_min_messages
              - fromFieldPath: spec.parameters.logMinMessages
                toFieldPath: spec.forProvider.parameters.pg_log_min_messages
              - fromFieldPath: spec.parameters.logMinErrorStatement
                toFieldPath: spec.forProvider.parameters.pg_log_min_error_statement
              - fromFieldPath: spec.parameters.logStatement
                toFieldPath: spec.forProvider.parameters.log_statement
              - fromFieldPath: spec.parameters.logErrorVerbosity
                toFieldPath: spec.forProvider.parameters.log_error_verbosity

              - type: ToCompositeFieldPath
                fromFieldPath: status.atProvider.createdAt
                toFieldPath: status.managed.createdAt
              - type: ToCompositeFieldPath
                fromFieldPath: status.atProvider.provisionedAt
                toFieldPath: status.managed.provisionedAt
              - type: ToCompositeFieldPath
                fromFieldPath: status.atProvider.state
                toFieldPath: status.managed.state
              - type: ToCompositeFieldPath
                fromFieldPath: status.atProvider.updatedAt
                toFieldPath: status.managed.updatedAt
              - type: ToCompositeFieldPath
                fromFieldPath: status.conditions
                toFieldPath: status.managed.conditions
