apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: a9s-postgresql
spec:
  compositeTypeRef:
    apiVersion: anynines.com/v1
    kind: XPostgresqlInstance
  mode: Pipeline
  pipeline:
    - step: patch-and-transform
      functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - name: a9s-postgresql
            base:
              apiVersion: dataservices.anynines.com/v1
              kind: ServiceInstance
              spec:
                forProvider:
                  # acceptsIncomplete indicates if the service broker can fulfill a
                  # request asynchronously. Since the anynines-provider controller
                  # reconciles the resources asynchronously, if 'acceptsIncomplete' is
                  # not specified by the user, it will default to 'true'.
                  acceptsIncomplete: true
                  # OrganizationGUID is the platform GUID for the organization under
                  # which the service is to be provisioned. This value is specific to
                  # Cloud Foundry.
                  organizationGuid: a1d46b5c-b639-4f43-85c7-e9a0e5f01f75
                  # SpaceGUID is the identifier for the project space within the
                  # platform organization. This value is specific to Cloud Foundry.
                  spaceGuid: 1bf71cf3-9017-4846-bffc-b9b31872bfaf
                providerConfigRef:
                  name: postgresql-service-broker
            patches:
              - fromFieldPath: metadata.labels[crossplane.io/claim-namespace]
                toFieldPath: metadata.labels[crossplane.io/claim-namespace]
              - fromFieldPath: metadata.labels[crossplane.io/claim-name]
                toFieldPath: metadata.labels[crossplane.io/claim-name]
              - fromFieldPath: spec.service
                toFieldPath: spec.forProvider.serviceName
              - fromFieldPath: spec.plan
                toFieldPath: spec.forProvider.planName
              - fromFieldPath: spec.acceptsIncomplete
                toFieldPath: spec.forProvider.acceptsIncomplete

              - fromFieldPath: spec.parameters.dataChecksums
                toFieldPath: spec.forProvider.parameters.dataChecksums
              - fromFieldPath: spec.parameters.maxConnections
                toFieldPath: spec.forProvider.parameters.maxConnections
              - fromFieldPath: spec.parameters.effectiveCacheSize
                toFieldPath: spec.forProvider.parameters.effectiveCacheSize
              - fromFieldPath: spec.parameters.workMem
                toFieldPath: spec.forProvider.parameters.workMem
              - fromFieldPath: spec.parameters.maintenanceWorkMem
                toFieldPath: spec.forProvider.parameters.maintenanceWorkMem
              - fromFieldPath: spec.parameters.tempFileLimit
                toFieldPath: spec.forProvider.parameters.tempFileLimit
              - fromFieldPath: spec.parameters.trackIoTiming
                toFieldPath: spec.forProvider.parameters.trackIoTiming
              - fromFieldPath: spec.parameters.archiveTimeout
                toFieldPath: spec.forProvider.parameters.archiveTimeout
              - fromFieldPath: spec.parameters.statementTimeout
                toFieldPath: spec.forProvider.parameters.statementTimeout
              - fromFieldPath: spec.parameters.idleInTransactionSessionTimeout
                toFieldPath: spec.forProvider.parameters.idleInTransactionSessionTimeout
              - fromFieldPath: spec.parameters.rolePrivileges
                toFieldPath: spec.forProvider.parameters.rolePrivileges
              - fromFieldPath: spec.parameters.walLevelLogical
                toFieldPath: spec.forProvider.parameters.walLevelLogical
              - fromFieldPath: spec.parameters.walWriterDelay
                toFieldPath: spec.forProvider.parameters.walWriterDelay
              - fromFieldPath: spec.parameters.maxReplicationSlots
                toFieldPath: spec.forProvider.parameters.maxReplicationSlots
              - fromFieldPath: spec.parameters.maxWalSenders
                toFieldPath: spec.forProvider.parameters.maxWalSenders
              - fromFieldPath: spec.parameters.synchronousCommit
                toFieldPath: spec.forProvider.parameters.synchronousCommit
              - fromFieldPath: spec.parameters.clientMinMessages
                toFieldPath: spec.forProvider.parameters.clientMinMessages
              - fromFieldPath: spec.parameters.logMinMessages
                toFieldPath: spec.forProvider.parameters.pgLogMinMessages
              - fromFieldPath: spec.parameters.logMinErrorStatement
                toFieldPath: spec.forProvider.parameters.pgLogMinErrorStatement
              - fromFieldPath: spec.parameters.logStatement
                toFieldPath: spec.forProvider.parameters.logStatement
              - fromFieldPath: spec.parameters.logErrorVerbosity
                toFieldPath: spec.forProvider.parameters.logErrorVerbosity

              - type: ToCompositeFieldPath
                fromFieldPath: status.atProvider.createdAt
                toFieldPath: status.managed.createdAt
              - type: ToCompositeFieldPath
                fromFieldPath: status.atProvider.provisionedAt
                toFieldPath: status.managed.provisionedAt
              - type: ToCompositeFieldPath
                fromFieldPath: status.atProvider.state
                toFieldPath: status.managed.state
              - type: ToCompositeFieldPath
                fromFieldPath: status.atProvider.updatedAt
                toFieldPath: status.managed.updatedAt
              - type: ToCompositeFieldPath
                fromFieldPath: status.conditions
                toFieldPath: status.managed.conditions
