apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - crossplane-api/deploy
  - https://anynines-artifacts.s3.eu-central-1.amazonaws.com/central-management/v1.3.0/crds.yaml
  - bind/contrib/example-backend/deploy/01-clusterrole.yaml
