apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - crossplane-api/deploy
  - https://raw.githubusercontent.com/anynines/klutchio/refs/heads/main/bind/deploy/crd/klutch.anynines.com_apiservicebindings.yaml
  - https://raw.githubusercontent.com/anynines/klutchio/refs/heads/main/bind/deploy/crd/klutch.anynines.com_apiserviceexportrequests.yaml
  - https://raw.githubusercontent.com/anynines/klutchio/refs/heads/main/bind/deploy/crd/klutch.anynines.com_apiserviceexports.yaml
  - https://raw.githubusercontent.com/anynines/klutchio/refs/heads/main/bind/deploy/crd/klutch.anynines.com_apiservicenamespaces.yaml
  - https://raw.githubusercontent.com/anynines/klutchio/refs/heads/main/bind/deploy/crd/klutch.anynines.com_clusterbindings.yaml
  - https://raw.githubusercontent.com/anynines/klutchio/refs/heads/main/bind/contrib/deploy/crd/example-backend.klutch.anynines.com_apiserviceexporttemplates.yaml
  - bind/contrib/example-backend/deploy/01-clusterrole.yaml
