/*
Copyright The Kube Bind Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"

	bindv1alpha1 "github.com/anynines/klutchio/bind/pkg/apis/bind/v1alpha1"
	scheme "github.com/anynines/klutchio/bind/pkg/client/clientset/versioned/scheme"
)

// APIServiceBindingsGetter has a method to return a APIServiceBindingInterface.
// A group's client should implement this interface.
type APIServiceBindingsGetter interface {
	APIServiceBindings() APIServiceBindingInterface
}

// APIServiceBindingInterface has methods to work with APIServiceBinding resources.
type APIServiceBindingInterface interface {
	Create(ctx context.Context, aPIServiceBinding *bindv1alpha1.APIServiceBinding, opts v1.CreateOptions) (*bindv1alpha1.APIServiceBinding, error)
	Update(ctx context.Context, aPIServiceBinding *bindv1alpha1.APIServiceBinding, opts v1.UpdateOptions) (*bindv1alpha1.APIServiceBinding, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, aPIServiceBinding *bindv1alpha1.APIServiceBinding, opts v1.UpdateOptions) (*bindv1alpha1.APIServiceBinding, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*bindv1alpha1.APIServiceBinding, error)
	List(ctx context.Context, opts v1.ListOptions) (*bindv1alpha1.APIServiceBindingList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *bindv1alpha1.APIServiceBinding, err error)
	APIServiceBindingExpansion
}

// aPIServiceBindings implements APIServiceBindingInterface
type aPIServiceBindings struct {
	*gentype.ClientWithList[*bindv1alpha1.APIServiceBinding, *bindv1alpha1.APIServiceBindingList]
}

// newAPIServiceBindings returns a APIServiceBindings
func newAPIServiceBindings(c *KlutchBindV1alpha1Client) *aPIServiceBindings {
	return &aPIServiceBindings{
		gentype.NewClientWithList[*bindv1alpha1.APIServiceBinding, *bindv1alpha1.APIServiceBindingList](
			"apiservicebindings",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *bindv1alpha1.APIServiceBinding { return &bindv1alpha1.APIServiceBinding{} },
			func() *bindv1alpha1.APIServiceBindingList { return &bindv1alpha1.APIServiceBindingList{} },
		),
	}
}
