/*
Copyright The Kube Bind Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"

	examplebackendv1alpha1 "github.com/anynines/klutchio/bind/contrib/example-backend/apis/examplebackend/v1alpha1"
)

// APIServiceExportTemplateLister helps list APIServiceExportTemplates.
// All objects returned here must be treated as read-only.
type APIServiceExportTemplateLister interface {
	// List lists all APIServiceExportTemplates in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*examplebackendv1alpha1.APIServiceExportTemplate, err error)
	// APIServiceExportTemplates returns an object that can list and get APIServiceExportTemplates.
	APIServiceExportTemplates(namespace string) APIServiceExportTemplateNamespaceLister
	APIServiceExportTemplateListerExpansion
}

// aPIServiceExportTemplateLister implements the APIServiceExportTemplateLister interface.
type aPIServiceExportTemplateLister struct {
	listers.ResourceIndexer[*examplebackendv1alpha1.APIServiceExportTemplate]
}

// NewAPIServiceExportTemplateLister returns a new APIServiceExportTemplateLister.
func NewAPIServiceExportTemplateLister(indexer cache.Indexer) APIServiceExportTemplateLister {
	return &aPIServiceExportTemplateLister{listers.New[*examplebackendv1alpha1.APIServiceExportTemplate](indexer, examplebackendv1alpha1.Resource("apiserviceexporttemplate"))}
}

// APIServiceExportTemplates returns an object that can list and get APIServiceExportTemplates.
func (s *aPIServiceExportTemplateLister) APIServiceExportTemplates(namespace string) APIServiceExportTemplateNamespaceLister {
	return aPIServiceExportTemplateNamespaceLister{listers.NewNamespaced[*examplebackendv1alpha1.APIServiceExportTemplate](s.ResourceIndexer, namespace)}
}

// APIServiceExportTemplateNamespaceLister helps list and get APIServiceExportTemplates.
// All objects returned here must be treated as read-only.
type APIServiceExportTemplateNamespaceLister interface {
	// List lists all APIServiceExportTemplates in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*examplebackendv1alpha1.APIServiceExportTemplate, err error)
	// Get retrieves the APIServiceExportTemplate from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*examplebackendv1alpha1.APIServiceExportTemplate, error)
	APIServiceExportTemplateNamespaceListerExpansion
}

// aPIServiceExportTemplateNamespaceLister implements the APIServiceExportTemplateNamespaceLister
// interface.
type aPIServiceExportTemplateNamespaceLister struct {
	listers.ResourceIndexer[*examplebackendv1alpha1.APIServiceExportTemplate]
}
