kind: APIServiceExportTemplate
apiVersion: example-backend.klutch.anynines.com/v1alpha1
metadata:
  name: "backups"
  namespace: crossplane-system
spec:
  APIServiceSelector:
    resource: backups
    group: anynines.com
