kind: APIServiceExportTemplate
apiVersion: example-backend.klutch.anynines.com/v1alpha1
metadata:
  name: keyvalueinstances
  namespace: crossplane-system
spec:
  APIServiceSelector:
    resource: keyvalueinstances
    group: anynines.com
