kind: APIServiceExportTemplate
apiVersion: example-backend.klutch.anynines.com/v1alpha1
metadata:
  name: logme2instances
  namespace: crossplane-system
spec:
  APIServiceSelector:
    resource: logme2instances
    group: anynines.com
