kind: APIServiceExportTemplate
apiVersion: bind.anynines.com/v1alpha1
metadata:
  name: mariadbinstances
  namespace: crossplane-system
spec:
  APIServiceSelector:
    resource: mariadbinstances
    group: anynines.com
