kind: APIServiceExportTemplate
apiVersion: example-backend.klutch.anynines.com/v1alpha1
metadata:
  name: messaginginstances
  namespace: crossplane-system
spec:
  APIServiceSelector:
    resource: messaginginstances
    group: anynines.com
