kind: APIServiceExportTemplate
apiVersion: example-backend.klutch.anynines.com/v1alpha1
metadata:
  name: mongodbinstances
  namespace: crossplane-system
spec:
  APIServiceSelector:
    resource: mongodbinstances
    group: anynines.com
