kind: APIServiceExportTemplate
apiVersion: example-backend.klutch.anynines.com/v1alpha1
metadata:
  name: "restores"
  namespace: crossplane-system
spec:
  APIServiceSelector:
    resource: restores
    group: anynines.com
