kind: APIServiceExportTemplate
apiVersion: example-backend.klutch.anynines.com/v1alpha1
metadata:
  name: searchinstances
  namespace: crossplane-system
spec:
  APIServiceSelector:
    resource: searchinstances
    group: anynines.com
