apiVersion: dataservices.anynines.com/v1
kind: Backup
metadata:
  name: backup-postgresql-sample-sadkl23
  namespace: default
  labels:
    crossplane.io/composite: backup-postgresql-sample
spec:
  forProvider:
    instanceName: example-postgresql-instance
  providerConfigRef:
    name: postgresql-backup-manager
