apiVersion: dataservices.anynines.com/v1
kind: Restore
metadata:
  name: restore-postgresql-sample-kjsdfkj
  namespace: default
  labels:
    crossplane.io/composite: restore-postgresql-sample
spec:
  forProvider:
    backupName: backup-postgresql-sample
  providerConfigRef:
    name: postgresql-backup-manager
