apiVersion: dataservices.anynines.com/v1
kind: ServiceBinding
metadata:
  name: example-postgresql-sb-jdkfshjk
  labels:
    crossplane.io/claim-name: example-postgresql-sb
    crossplane.io/claim-namespace: default
    crossplane.io/composite: example-postgresql-sb-ajtsd
spec:
  forProvider:
    acceptsIncomplete: false
    instanceName: example-postgresql-instance
  writeConnectionSecretToRef:
    namespace: crossplane-system
    name: example-postgresql-sb-creds
  providerConfigRef:
    name: postgresql-service-broker

