/*
Copyright The Kube Bind Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"

	examplebackendv1alpha1 "github.com/anynines/klutchio/bind/contrib/example-backend/apis/examplebackend/v1alpha1"
	scheme "github.com/anynines/klutchio/bind/contrib/example-backend/client/clientset/versioned/scheme"
)

// APIServiceExportTemplatesGetter has a method to return a APIServiceExportTemplateInterface.
// A group's client should implement this interface.
type APIServiceExportTemplatesGetter interface {
	APIServiceExportTemplates(namespace string) APIServiceExportTemplateInterface
}

// APIServiceExportTemplateInterface has methods to work with APIServiceExportTemplate resources.
type APIServiceExportTemplateInterface interface {
	Create(ctx context.Context, aPIServiceExportTemplate *examplebackendv1alpha1.APIServiceExportTemplate, opts v1.CreateOptions) (*examplebackendv1alpha1.APIServiceExportTemplate, error)
	Update(ctx context.Context, aPIServiceExportTemplate *examplebackendv1alpha1.APIServiceExportTemplate, opts v1.UpdateOptions) (*examplebackendv1alpha1.APIServiceExportTemplate, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, aPIServiceExportTemplate *examplebackendv1alpha1.APIServiceExportTemplate, opts v1.UpdateOptions) (*examplebackendv1alpha1.APIServiceExportTemplate, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*examplebackendv1alpha1.APIServiceExportTemplate, error)
	List(ctx context.Context, opts v1.ListOptions) (*examplebackendv1alpha1.APIServiceExportTemplateList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *examplebackendv1alpha1.APIServiceExportTemplate, err error)
	APIServiceExportTemplateExpansion
}

// aPIServiceExportTemplates implements APIServiceExportTemplateInterface
type aPIServiceExportTemplates struct {
	*gentype.ClientWithList[*examplebackendv1alpha1.APIServiceExportTemplate, *examplebackendv1alpha1.APIServiceExportTemplateList]
}

// newAPIServiceExportTemplates returns a APIServiceExportTemplates
func newAPIServiceExportTemplates(c *ExampleBackendV1alpha1Client, namespace string) *aPIServiceExportTemplates {
	return &aPIServiceExportTemplates{
		gentype.NewClientWithList[*examplebackendv1alpha1.APIServiceExportTemplate, *examplebackendv1alpha1.APIServiceExportTemplateList](
			"apiserviceexporttemplates",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *examplebackendv1alpha1.APIServiceExportTemplate {
				return &examplebackendv1alpha1.APIServiceExportTemplate{}
			},
			func() *examplebackendv1alpha1.APIServiceExportTemplateList {
				return &examplebackendv1alpha1.APIServiceExportTemplateList{}
			},
		),
	}
}
