apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xpolicies.anynines.com
spec:
  group: anynines.com
  names:
    kind: XPolicy
    plural: xpolicies
  claimNames:
    kind: Policy
    plural: policies
  defaultCompositionRef:
    name: a8s-iam-policy
  defaultCompositeDeletePolicy: Foreground
  versions:
  - name: v1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        properties:
          spec:
            type: object
            properties:
              policy:
                properties:
                  path:
                    description: |
                        Path in which to create the policy
                    type: string
                  description:
                    description: Description of the policy
                    type: string
                  name:
                    description: Name of the policy
                    type: string
                  statements:
                    description: The Statement element can contain a single statement or an array of individual statements
                    items:
                      properties:
                        actions:
                          description: Action describes the specific action or actions that will be allowed like list, get, update, delete
                          items:
                            type: string
                          type: array
                        buckets:
                          description: Buckets defines the object or objects that the statement applies to.
                          items:
                            type: string
                          type: array
                      type: object
                    type: array
                required:
                - name
                - statements
                type: object
              tags:
                description: |
                    Key-value map of resource tags.
                type: object
            required:
              - policy
          status:
            type: object
            properties:
              managed:
                type: object
                x-kubernetes-preserve-unknown-fields: true
