apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xpolicies.anynines.com
spec:
  group: anynines.com
  names:
    kind: XPolicy
    plural: xpolicies
  claimNames:
    kind: Policy
    plural: policies
  defaultCompositionRef:
    name: a8s-iam-policy
  defaultCompositeDeletePolicy: Foreground
  versions:
  - name: v1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        properties:
          spec:
            type: object
            properties:
              resource:
                description: |
                  The Resource defines the object or objects that the statement applies to. Statements must include either a Resource or a NotResource element
                type: string
              path:
                description: |
                    Path in which to create the policy
                type: string
              description:
                description: |
                    Description of the policy
                type: string
              actions:
                description: |
                    Action describes the specific action or actions that will be allowed like Get, List, etc..
                type: array
                items:
                  type: string
              tags:
                description: |
                    Key-value map of resource tags.
                type: object
            required:
              - resource
              - actions
          status:
            type: object
            properties:
              managed:
                type: object
                x-kubernetes-preserve-unknown-fields: true
