apiVersion: anynines.com/v1
kind: Restore
metadata:
  name: example-a9s-logme2
spec:
  backupRef: example-a9s-logme2
  serviceInstanceType: logme2
  crossplane:
    compositionRef:
      name: a9s-restore
