apiVersion: anynines.com/v1
kind: ServiceBinding
metadata:
  name: example-a9s-logme2
  namespace: default
spec:
  crossplane:
    compositionRef:
      name: a9s-servicebinding
  # instanceName indicates the name of the DataServiceInstance
  instanceRef: example-a9s-logme2
  serviceInstanceType: logme2 # Adjust for each Service Instance type
