apiVersion: v1
kind: Secret
metadata:
  namespace: crossplane-system
  name: mariadb-service-broker-credentials
type: Opaque
data:
  username: $BASE64ENCODED_MARIADB_SERVICE_BROKER_USERNAME
  password: $BASE64ENCODED_MARIADB_SERVICE_BROKER_PASSWORD
---
apiVersion: dataservices.anynines.com/v1
kind: ProviderConfig
metadata:
  name: mariadb-service-broker
spec:
  url: "http://dockerhost:9589" # Connect to k8s service
  providerCredentials:
    source: Secret
    username:
      secretRef:
        namespace: crossplane-system
        name: mariadb-service-broker-credentials
        key: username
    password:
      secretRef:
        namespace: crossplane-system
        name: mariadb-service-broker-credentials
        key: password
---
apiVersion: v1
kind: Secret
metadata:
  namespace: crossplane-system
  name: mariadb-backup-manager-credentials
type: Opaque
data:
  username: $BASE64ENCODED_MARIADB_BACKUP_MANAGER_USERNAME
  password: $BASE64ENCODED_MARIADB_BACKUP_MANAGER_PASSWORD
---
apiVersion: dataservices.anynines.com/v1
kind: ProviderConfig
metadata:
  name: mariadb-backup-manager
spec:
  url: "http://dockerhost:9588" # Connect to k8s service
  providerCredentials:
    source: Secret
    username:
      secretRef:
        namespace: crossplane-system
        name: mariadb-backup-manager-credentials
        key: username
    password:
      secretRef:
        namespace: crossplane-system
        name: mariadb-backup-manager-credentials
        key: password
