/*
Copyright The Kube Bind Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"

	bindv1alpha1 "github.com/anynines/klutchio/bind/pkg/apis/bind/v1alpha1"
)

// AppClusterBindingLister helps list AppClusterBindings.
// All objects returned here must be treated as read-only.
type AppClusterBindingLister interface {
	// List lists all AppClusterBindings in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*bindv1alpha1.AppClusterBinding, err error)
	// AppClusterBindings returns an object that can list and get AppClusterBindings.
	AppClusterBindings(namespace string) AppClusterBindingNamespaceLister
	AppClusterBindingListerExpansion
}

// appClusterBindingLister implements the AppClusterBindingLister interface.
type appClusterBindingLister struct {
	listers.ResourceIndexer[*bindv1alpha1.AppClusterBinding]
}

// NewAppClusterBindingLister returns a new AppClusterBindingLister.
func NewAppClusterBindingLister(indexer cache.Indexer) AppClusterBindingLister {
	return &appClusterBindingLister{listers.New[*bindv1alpha1.AppClusterBinding](indexer, bindv1alpha1.Resource("appclusterbinding"))}
}

// AppClusterBindings returns an object that can list and get AppClusterBindings.
func (s *appClusterBindingLister) AppClusterBindings(namespace string) AppClusterBindingNamespaceLister {
	return appClusterBindingNamespaceLister{listers.NewNamespaced[*bindv1alpha1.AppClusterBinding](s.ResourceIndexer, namespace)}
}

// AppClusterBindingNamespaceLister helps list and get AppClusterBindings.
// All objects returned here must be treated as read-only.
type AppClusterBindingNamespaceLister interface {
	// List lists all AppClusterBindings in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*bindv1alpha1.AppClusterBinding, err error)
	// Get retrieves the AppClusterBinding from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*bindv1alpha1.AppClusterBinding, error)
	AppClusterBindingNamespaceListerExpansion
}

// appClusterBindingNamespaceLister implements the AppClusterBindingNamespaceLister
// interface.
type appClusterBindingNamespaceLister struct {
	listers.ResourceIndexer[*bindv1alpha1.AppClusterBinding]
}
