apiVersion: anynines.com/v1
kind: Restore
metadata:
  name: example-a9s-messaging
spec:
    backupRef: example-a9s-messaging
    serviceInstanceType: messaging
    # If no compositionRef is provided, the default choice will be a8s-restore.
    compositionRef:
      name: a9s-restore
