apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xmariadbinstances.anynines.com
spec:
  group: anynines.com
  names:
    kind: XMariadbInstance
    plural: xmariadbinstances
  claimNames:
    kind: MariadbInstance
    plural: mariadbinstances
  defaultCompositionRef:
    name: a9s-mariadb
  defaultCompositeDeletePolicy: Foreground
  versions:
    - name: v1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          supported:
            - plans:
                &mariadbPlans [
                  "mariadb-single-nano",
                  "mariadb-single-small",
                  "mariadb-single-big",
                  "mariadb-single-nano-ssl",
                  "mariadb-single-small-ssl",
                  "mariadb-single-big-ssl",
                  "mariadb-cluster-small",
                  "mariadb-cluster-big",
                  "mariadb-cluster-small-ssl",
                  "mariadb-cluster-big-ssl",
                ]
            - services: &mariadbServices ["a9s-mariadb106", "a9s-mariadb1011"]
          properties:
            spec:
              x-kubernetes-validations:
                # MariaDB 10.11 only supports ssl plans.
                - rule: "(self.service == 'a9s-mariadb1011' &&
                    self.plan.contains('ssl')) ||
                    self.service == 'a9s-mariadb106'"
                  message: "MariaDB v10.11 only supports ssl plans"
              properties:
                acceptsIncomplete:
                  type: boolean
                service:
                  type: string
                  enum: *mariadbServices
                  x-kubernetes-validations:
                    # Validation to check that service can't be updated.
                    - rule: "self == oldSelf"
                      message: "Service is an immutable field"
                plan:
                  description:
                    Plan specifies the service plan. There are options
                    for single or clustered Data Service Instances and options
                    for different underlying computing resources (e.g.
                    mariadb-cluster-small).
                  type: string
                  enum: *mariadbPlans
                  x-kubernetes-validations:
                    # Validate that only upgrades from smaller to bigger DS instance
                    # sizes are allowed.
                    - rule:
                        "!(self.contains('nano') && oldSelf.contains('small')) &&
                        !(self.contains('nano') && oldSelf.contains('big')) &&
                        !(self.contains('small') && oldSelf.contains('big'))"
                      message:
                        "Transition from bigger to smaller plan size is not
                        supported."
                    # Validate that only migrations from single to replicated DS
                    # instance are allowed.
                    - rule: "!(self.contains('-single-') && oldSelf.contains('-cluster-'))"
                      message: "Migration from replicated to single Data Service
                        Instance is not supported."
                    - rule: "oldSelf.contains('ssl') == self.contains('ssl')"
                      message:
                        "Plan migrations not possible from Non-SSL to SSL and
                        SSL to Non-SSL"

                # Custom Parameters
                parameters:
                  type: object
                  properties:
                    binlogExpireDays:
                      type: integer
                      description: |
                        The number of days that the binary log should be kept
                        on the instance that is running MariaDB before purging.
                      minimum: 1
                    databases:
                      description: |
                        List of the names of the databases that should exist in
                        the instance other than the default database.
                        See https://docs.anynines.com/docs/application-developer/a9s-mariadb/a9s-ad-mariadb-custom-parameters/#databases-parameter
                      type: array
                      items:
                        type: string
                    grantPerformanceSchemaPermissions:
                      description: |
                        Whether to grant Performance Schema permissions to the
                        Cloud Foundry (CF) binding credentials.
                      type: boolean
              required:
                - service
                - plan
            status:
              type: object
              properties:
                managed:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
      additionalPrinterColumns:
        - name: ManagedResource
          type: string
          jsonPath: ".status.managed.state"
