apiVersion: anynines.com/v1
kind: ServiceBinding
metadata:
  name: example-a9s-mongodb
  namespace: default
spec:
  crossplane:
    compositionRef:
      name: a9s-servicebinding
  # instanceName indicates the name of the DataServiceInstance
  instanceRef: example-a9s-mongodb
  serviceInstanceType: mongodb # Adjust for each Service Instance type
