apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: klutch-binder
rules:
  - apiGroups:
      - "klutch.anynines.com"
    resources:
      - "apiserviceexportrequests"
    verbs: ["create", "delete", "patch", "update", "get", "list", "watch"]
  - apiGroups:
      - ""
    resources:
      - "namespaces"
    verbs: ["get"]
  - apiGroups:
      - ""
    resources:
      - "secrets"
    verbs: ["get", "watch", "list"]
  - apiGroups:
      - "klutch.anynines.com"
    resources:
      - "clusterbindings"
    verbs: ["get", "watch", "list"]
  - apiGroups:
      - "klutch.anynines.com"
    resources:
      - "clusterbindings/status"
    verbs: ["get", "patch", "update"]
  - apiGroups:
      - "klutch.anynines.com"
    resources:
      - "apiserviceexports"
    verbs: ["get", "watch", "list"]
  - apiGroups:
      - "klutch.anynines.com"
    resources:
      - "apiserviceexports/status"
    verbs: ["get", "patch", "update"]
  - apiGroups:
      - "klutch.anynines.com"
    resources:
      - "apiservicenamespaces"
    verbs: ["create", "delete", "patch", "update", "get", "list", "watch"]
