apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: a9s-search
spec:
  compositeTypeRef:
    apiVersion: anynines.com/v1
    kind: XSearchInstance
  mode: Pipeline
  pipeline:
    - step: patch-and-transform
      functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - name: a9s-search
            base:
              apiVersion: dataservices.anynines.com/v1
              kind: ServiceInstance
              spec:
                forProvider:
                  # acceptsIncomplete indicates if the service broker can fulfill a
                  # request asynchronously. Since the anynines-provider controller
                  # reconciles the resources asynchronously, if 'acceptsIncomplete' is
                  # not specified by the user, it will default to 'true'.
                  acceptsIncomplete: true
                  # OrganizationGUID is the platform GUID for the organization under
                  # which the service is to be provisioned. This value is specific to
                  # Cloud Foundry.
                  organizationGuid: a1d46b5c-b639-4f43-85c7-e9a0e5f01f75
                  # SpaceGUID is the identifier for the project space within the
                  # platform organization. This value is specific to Cloud Foundry.
                  spaceGuid: 1bf71cf3-9017-4846-bffc-b9b31872bfaf
                providerConfigRef:
                  name: search-service-broker
            patches:
              - fromFieldPath: metadata.labels[crossplane.io/claim-namespace]
                toFieldPath: metadata.labels[crossplane.io/claim-namespace]
              - fromFieldPath: metadata.labels[crossplane.io/claim-name]
                toFieldPath: metadata.labels[crossplane.io/claim-name]
              - fromFieldPath: spec.service
                toFieldPath: spec.forProvider.serviceName
              - fromFieldPath: spec.plan
                toFieldPath: spec.forProvider.planName
              - fromFieldPath: spec.acceptsIncomplete
                toFieldPath: spec.forProvider.acceptsIncomplete
              - type: ToCompositeFieldPath
                fromFieldPath: status.atProvider.createdAt
                toFieldPath: status.managed.createdAt
              - type: ToCompositeFieldPath
                fromFieldPath: status.atProvider.provisionedAt
                toFieldPath: status.managed.provisionedAt
              - type: ToCompositeFieldPath
                fromFieldPath: status.atProvider.state
                toFieldPath: status.managed.state
              - type: ToCompositeFieldPath
                fromFieldPath: status.atProvider.updatedAt
                toFieldPath: status.managed.updatedAt
              - type: ToCompositeFieldPath
                fromFieldPath: status.conditions
                toFieldPath: status.managed.conditions
