apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
# This is a short-term solution. The a9s and a8s will soon share a common XRD.
metadata:
  name: xsearchinstances.anynines.com
spec:
  group: anynines.com
  names:
    kind: XSearchInstance
    plural: xsearchinstances
  claimNames:
    kind: SearchInstance
    plural: searchinstances
  defaultCompositionRef:
    name: a9s-search
  defaultCompositeDeletePolicy: Foreground
  versions:
  - name: v1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        supported:
          - plans: &searchPlans ["search-cluster-small-ssl",
              "search-cluster-medium-ssl", "search-cluster-big-ssl",
              "search-single-nano-ssl","search-single-small-ssl",
              "search-single-medium-ssl", "search-single-big-ssl"]
          - services: &searchServices ["a9s-search2"]
        properties:
          spec:
            properties:
              acceptsIncomplete:
                type: boolean
              service:
                type: string
                enum: *searchServices
                x-kubernetes-validations:
                # Validation to check that service can't be updated.
                - rule: "self == oldSelf"
                  message: "Service is an immutable field"
              plan:
                description: Plan specifies the service plan. There are options
                  for single or clustered Data Service Instances and options for
                  different underlying computing resources (e.g.
                  search-cluster-small).
                type: string
                enum: *searchPlans
                x-kubernetes-validations:
                # Validate that only upgrades from smaller to bigger DS instance
                # sizes are allowed.
                - rule: "!(self.contains('small') && oldSelf.contains('medium')) &&
                    !(self.contains('small') && oldSelf.contains('big')) &&
                    !(self.contains('medium') && oldSelf.contains('big'))"
                  message: "Transition from bigger to smaller plan size is not
                    supported."
                # We must use separate rules to avoid reaching the rule complexity limit
                - rule: "!(self.contains('nano') && oldSelf.contains('small')) &&
                    !(self.contains('nano') && oldSelf.contains('medium'))&&
                    !(self.contains('nano') && oldSelf.contains('big'))"
                  message: "Transition from bigger to smaller plan size is not
                    supported."
                # Validate that only migrations from single to clustered DS
                # instance are allowed.
                - rule: "!(self.contains('-single-') && oldSelf.contains('-cluster-'))"
                  message: "Migration from clustered to single Data Service
                    Instance is not supported."

              parameters:
                type: object
                properties:
                  javaHeapspace:
                    description: |
                      The amount of memory (in MB) allocated as heap by the JVM for OpenSearch.
                      May not be greater than 50% of VM memory (check your plan details).
                      If not set, 46% of available memory will be used.
                    type: integer
                    x-kubernetes-validations:
                    - rule: "self >= 256"
                      message: "Must be greater than or equal to 256"
                  javaMaxmetaspace:
                    description: |
                      The amount of memory (in MB) used by the JVM to store metadata for OpenSearch.
                    type: integer
                    x-kubernetes-validations:
                    - rule: "self >= 256"
                      message: "Must be greater than or equal to 256"
                    - rule: "self <= 1024"
                      message: "Must be smaller than or equal to 1024"
                  javaGarbageCollector:
                    description: |
                      The JVM Garbage Collector to be used for OpenSearch.
                    type: string
                    enum: ["UseSerialGC", "UseParallelGC", "UseParallelOldGC", "UseG1GC"]
                  tlsProtocols:
                    description: |
                      You can specify the allowed TLS protocols via the custom parameter.
                      The custom parameter correlates with OpenSearch's configuration parameters plugins.security.ssl.http.enabled_protocols and plugins.security.ssl.transport.enabled_protocols.
                      See https://opensearch.org/docs/latest/security-plugin/configuration/tls/#advanced-enabled-ciphers-and-protocols

                      An array with protocol versions is expected. Only Java format is supported. The allowed protocol version values are TLSv1.3 and TLSv1.2.
                    type: array
                    items:
                      type: string
                      enum: ["TLSv1.2", "TLSv1.3"]
                  tlsCiphers:
                    description: |
                      You can limit the TLS ciphers via the custom parameter.
                      The custom parameter correlates with OpenSearch's configuration parameters plugins.security.ssl.http.enabled_ciphers and plugins.security.ssl.transport.enabled_ciphers.
                      See https://opensearch.org/docs/latest/security-plugin/configuration/tls/#advanced-enabled-ciphers-and-protocols
                      
                      An array with cipher names is expected. Only Java format is supported.
                      WARNING: There is no validation enabled for the user provided value and therefore existing instances can break when applying this parameter.
                    type: array
                    items:
                      type: string

            required:
              - service
              - plan
          status:
            type: object
            properties:
              managed:
                type: object
                x-kubernetes-preserve-unknown-fields: true
    additionalPrinterColumns:
    - name: ManagedResource
      type: string
      jsonPath: ".status.managed.state"
