apiVersion: anynines.com/v1
kind: Backup
metadata:
  name: example-a9s-postgresql
  namespace: default
spec:
  crossplane:
    compositionRef:
      name: a9s-backup
  instanceRef: example-a9s-postgresql
  serviceInstanceType: postgresql
