apiVersion: anynines.com/v1
kind: Restore
metadata:
  name: example-a9s-postgresql
  namespace: default  
spec:
    backupRef: example-a9s-postgresql
    serviceInstanceType: postgresql
    # If no compositionRef is provided, the default choice will be a8s-restore.
    compositionRef:
      name: a9s-restore
