apiVersion: anynines.com/v1
kind: PostgresqlInstance
metadata:
  name: example-a9s-postgresql-with-parameters
  namespace: default
spec:
  # Use a supported postgresql serviceName and planName
  service: a9s-postgresql15
  plan: postgresql-replica-small
  compositionRef:
    name: a9s-postgresql
  parameters:
    tempFileLimit: 4096
    trackIoTiming: "on"
    archiveTimeout: 700
    statementTimeout: 3000
    walWriterDelay: 400
    maxReplicationSlots: 12
    maxWalSenders: 12
    synchronousCommit: "local"
    clientMinMessages: LOG
    logMinMessages: NOTICE
    logMinErrorStatement: WARNING
    logStatement: ddl
    logErrorVerbosity: VERBOSE
    walLevelLogical: true
    # rolePrivileges: ["CREATEDB", "CREATEROLE","REPLICATION"] # Note: Make sure your broker is configured to enable role privileges before using this parameter.
