apiVersion: anynines.com/v1
kind: ServiceBinding
metadata:
  name: example-a9s-postgresql
  namespace: default
spec:
  # instanceRef indicates the name of the DataServiceInstance
  instanceRef: example-a9s-postgresql
  serviceInstanceType: postgresql # Adjust for each Service Instance type
  crossplane:
    compositionRef:
      name: a9s-servicebinding