apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: a8s-s3-servicebinding
spec:
  compositeTypeRef:
    apiVersion: anynines.com/v1
    kind: XServiceBinding
  resources:
    - name: a8s-s3-bucket-policy
      base:
        apiVersion: s3.aws.upbound.io/v1beta1
        kind: BucketPolicy
        spec:
          providerConfigRef:
            name: aws-s3-provider
          forProvider:
            bucketRef.name: "s3-bucket-name"
            region: "eu-central-1"
            policy: >
              {
                  "Id": "Policy1712922854010",
                  "Version": "2012-10-17",
                  "Statement": [
                    {
                      "Sid": "Stmt1712922850476",
                      "Action": "s3:*",
                      "Effect": "Deny",
                      "Resource": "arn:aws:s3:::*/*",
                      "Principal": "*"
                    }
                  ]
              }
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.region"
          toFieldPath: "spec.forProvider.region"
        - fromFieldPath: "spec.instanceRef"
          toFieldPath: "spec.forProvider.bucketRef.name"
        - fromFieldPath: "spec.policy"
          toFieldPath: "spec.forProvider.policy"