apiVersion: anynines.com/v1
kind: Backup
metadata:
  name: example-a9s-keyvalue
  namespace: default
spec:
  instanceRef: example-a9s-keyvalue
  serviceInstanceType: keyvalue
  crossplane:
    compositionRef:
      name: a9s-backup
