apiVersion: anynines.com/v1
kind: Restore
metadata:
  name: example-a9s-keyvalue
spec:
  backupRef: example-a9s-keyvalue
  serviceInstanceType: keyvalue
  crossplane:
    compositionRef:
      name: a9s-restore
