apiVersion: anynines.com/v1
kind: KeyvalueInstance
metadata:
  name: example-a9s-keyvalue
  namespace: default
spec:
  # Use a supported keyvalue serviceName and planName
  service: a9s-keyvalue8
  plan: keyvalue-single-small-ssl
  compositionRef:
    name: a9s-keyvalue
