apiVersion: anynines.com/v1
kind: PostgresqlInstance
metadata:
  name: example-a8s-postgresql
  namespace: default
spec:
  service: "a9s-postgresql13"
  plan: "postgresql-single-small"
  # expose is Optional, with the default value set to 'LoadBalancer'
  expose: "Internal"
  compositionRef:
    name: a8s-postgresql
