# This claim contains all possible parameters, with values *different* from their defaults.
# (excluding parameters not supported by a8s)
apiVersion: anynines.com/v1
kind: PostgresqlInstance
metadata:
  name: example-a8s-postgresql-parameters
  namespace: default
spec:
  service: "a9s-postgresql13"
  plan: "postgresql-single-small"
  # expose is Optional, with the default value set to 'LoadBalancer'
  expose: "Internal"
  parameters:
    maxConnections: 120
    tempFileLimit: 1024
    # make sure to specify this as a string (`on` in YAML is interpreted as a boolean)
    trackIoTiming: "on"
    archiveTimeout: 1000
    statementTimeout: 3000
    walWriterDelay: 400
    maxReplicationSlots: 12
    maxWalSenders: 12
    synchronousCommit: "local"
    sslCiphers: "NULL-MD5" # (bad example, but should work)
    sslMinProtocolVersion: "TLSv1"
    clientMinMessages: LOG
    logMinMessages: NOTICE
    logMinErrorStatement: WARNING
    logStatement: ddl
    logErrorVerbosity: TERSE
    maxLocksPerTransaction: 128
  compositionRef:
    name: a8s-postgresql
