apiVersion: anynines.com/v1
kind: ServiceBinding
metadata:
  name: example-a8s-postgresql
  namespace: default
spec:
  instanceRef: example-a8s-postgresql
  serviceInstanceType: postgresql
  #Optional
  #writeConnectionSecretToRef:
  #  name: example-connection
