/*
Copyright The Kube Bind Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"

	apisbindv1alpha1 "github.com/anynines/klutchio/bind/pkg/apis/bind/v1alpha1"
	versioned "github.com/anynines/klutchio/bind/pkg/client/clientset/versioned"
	internalinterfaces "github.com/anynines/klutchio/bind/pkg/client/informers/externalversions/internalinterfaces"
	bindv1alpha1 "github.com/anynines/klutchio/bind/pkg/client/listers/bind/v1alpha1"
)

// AppClusterBindingInformer provides access to a shared informer and lister for
// AppClusterBindings.
type AppClusterBindingInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() bindv1alpha1.AppClusterBindingLister
}

type appClusterBindingInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewAppClusterBindingInformer constructs a new informer for AppClusterBinding type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewAppClusterBindingInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredAppClusterBindingInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredAppClusterBindingInformer constructs a new informer for AppClusterBinding type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredAppClusterBindingInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KlutchBindV1alpha1().AppClusterBindings(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KlutchBindV1alpha1().AppClusterBindings(namespace).Watch(context.TODO(), options)
			},
		},
		&apisbindv1alpha1.AppClusterBinding{},
		resyncPeriod,
		indexers,
	)
}

func (f *appClusterBindingInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredAppClusterBindingInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *appClusterBindingInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apisbindv1alpha1.AppClusterBinding{}, f.defaultInformer)
}

func (f *appClusterBindingInformer) Lister() bindv1alpha1.AppClusterBindingLister {
	return bindv1alpha1.NewAppClusterBindingLister(f.Informer().GetIndexer())
}
