apiVersion: anynines.com/v1
kind: ServiceBinding
metadata:
  name: example-a9s-mariadb
  namespace: default
spec:
  # instanceRef indicates the name of the DataServiceInstance
  instanceRef: example-a9s-mariadb
  serviceInstanceType: mariadb # Adjust for each Service Instance type
  #Optional
  #writeConnectionSecretToRef:
  #  name: example-a9s-mariadb-creds
  crossplane:
    compositionRef:
      name: a9s-servicebinding
