apiVersion: anynines.com/v1
kind: MariadbInstance
metadata:
  name: example-a9s-mariadb-parameters
  namespace: default
spec:
  # Use a supported mariadb serviceName and planName
  service: a9s-mariadb106
  plan: mariadb-single-nano-ssl
  compositionRef:
    name: a9s-mariadb
  parameters:
    binlogExpireDays: 1
    databases: ["db1", "db2"]
    grantPerformanceSchemaPermissions: true

