apiVersion: anynines.com/v1
kind: ServiceBinding
metadata:
  name: example-a9s-mariadb
  namespace: default
spec:
  crossplane:
    compositionRef:
      name: a9s-servicebinding
  # instanceRef indicates the DataServiceInstance claim name
  instanceRef: example-a9s-mariadb
  serviceInstanceType: mariadb # Adjust for each Service Instance type
