apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xlogme2instances.anynines.com
spec:
  group: anynines.com
  names:
    kind: XLogme2Instance
    plural: xlogme2instances
  claimNames:
    kind: Logme2Instance
    plural: logme2instances
  defaultCompositionRef:
    name: a9s-logme2
  defaultCompositeDeletePolicy: Foreground
  versions:
  - name: v1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        supported:
          - plans: &logme2Plans ["logme-cluster-small-ssl", "logme-single-small-ssl"]
          - services: &logme2Services ["a9s-logme2"]
        properties:
          spec:
            properties:
              acceptsIncomplete:
                type: boolean
              service:
                type: string
                enum: *logme2Services
                x-kubernetes-validations:
                # Validation to check that service can't be updated.
                - rule: "self == oldSelf"
                  message: "Service is an immutable field"
              plan:
                description: Plan specifies the service plan. There are options
                  for single or clustered Data Service Instances and options for
                  different underlying computing resources (e.g.
                  logme2-cluster-small).
                type: string
                enum: *logme2Plans
                x-kubernetes-validations:
                # Validate that only migrations from single to clustered DS
                # instance are allowed.
                - rule: "!(self.contains('-single-') && oldSelf.contains('-cluster-'))"
                  message: "Migration from clustered to single Data Service
                    Instance is not supported."
                # Validate that only migrations from single to clustered DS
                # instance are allowed.
                - rule: "!(self.contains('-cluster-') && oldSelf.contains('-single-'))"
                  message: "Migration from single to clustered Data Service
                    Instance is not supported."

              # Custom configuration parameters
              parameters:
                type: object
                properties:
                  javaHeapspace:
                    description: |
                      The amount of memory (in MB) allocated as heap by the JVM for OpenSearch.
                      May not be greater than 50% of VM memory (check your plan details).
                      If not set, 46% of available memory will be used.
                    type: integer
                    x-kubernetes-validations:
                    - rule: "self >= 256"
                      message: "Must be greater than or equal to 256"
                  javaMaxmetaspace:
                    description: |
                      The amount of memory (in MB) used by the JVM to store metadata for OpenSearch.
                    type: integer
                    x-kubernetes-validations:
                    - rule: "self >= 256"
                      message: "Must be greater than or equal to 256"
                    - rule: "self <= 1024"
                      message: "Must be smaller than or equal to 1024"
                  javaGarbageCollector:
                    description: |
                      The JVM Garbage Collector to be used for OpenSearch.
                    type: string
                    enum: ["UseSerialGC", "UseParallelGC", "UseParallelOldGC", "UseG1GC"]
                  ismJobInterval:
                    description:
                      Time between executions of the Index State Management in minutes.
                    type: integer
                    x-kubernetes-validations:
                    - rule: "self > 0"
                      message: "Must be greater than 0"
                  ismDeletionAfter:
                    description:
                      Combination of an integer and a timerange when an index will be considered "old"
                      and can be deleted from OpenSearch. Possible values for the timerange are s, m, h and d
                    type: string
                  ismJitter:
                    description:
                      Jitter of the execution time (job_interval)
                      Read more at https://opensearch.org/docs/latest/im-plugin/ism/settings/ 
                    type: number
                    x-kubernetes-validations:
                    - rule: "self >= 0"
                      message: "Must be greater than or equal to 0"
                  opensearchTlsProtocols:
                    description: |
                      You can specify the allowed TLS protocols via the custom parameter.
                      The custom parameter correlates with OpenSearch's configuration parameters plugins.security.ssl.http.enabled_protocols and plugins.security.ssl.transport.enabled_protocols.
                      See https://opensearch.org/docs/latest/security-plugin/configuration/tls/#advanced-enabled-ciphers-and-protocols

                      An array with protocol versions is expected. Only Java format is supported. The allowed protocol version values are TLSv1.3 and TLSv1.2.
                    type: array
                    items:
                      type: string
                      enum: ["TLSv1.2", "TLSv1.3"]
                  opensearchTlsCiphers:
                    description: |
                      You can limit the TLS ciphers via the custom parameter.
                      The custom parameter correlates with OpenSearch's configuration parameters plugins.security.ssl.http.enabled_ciphers and plugins.security.ssl.transport.enabled_ciphers.
                      See https://opensearch.org/docs/latest/security-plugin/configuration/tls/#advanced-enabled-ciphers-and-protocols
                      
                      An array with cipher names is expected. Only Java format is supported.
                      WARNING: There is no validation enabled for the user provided value and therefore existing instances can break when applying this parameter.
                    type: array
                    items:
                      type: string
                  fluentdUdp:
                    description: |
                      This property specifies the port for the UDP endpoint of Fluentd. The default value is 514.
                    type: integer
                    x-kubernetes-validations:
                    - rule: "self > 0"
                      message: "Must be greater than 0"
                    - rule: "self <= 65535"
                      message: "Must be smaller than or equal to 65535"
                  fluentdTcp:
                    description: |
                      This property specifies the port for the unencrypted TCP endpoint of Fluentd. The default value is 0 (disabled).
                      The port of the UDP and unencrypted TCP endpoint can be the same, but do not have to be.
                    type: integer
                    x-kubernetes-validations:
                    - rule: "self > 0"
                      message: "Must be greater than 0"
                    - rule: "self <= 65535"
                      message: "Must be smaller than or equal to 65535"
                  fluentdTls:
                    description: |
                      This property specifies the port for the encrypted TCP endpoint of Fluentd. The default value is 6514.
                    type: integer
                    x-kubernetes-validations:
                    - rule: "self > 0"
                      message: "Must be greater than 0"
                    - rule: "self <= 65535"
                      message: "Must be smaller than or equal to 65535"
                  fluentdTlsCiphers:
                    description: |
                      This property specifies the allowed TLS ciphers for Fluentd. See the Fluentd documentation for more information https://docs.fluentd.org/configuration/transport-section#tls-setting
                      WARNING: This property is only type checked and not fully validated! The current validation only type checks for a string. Any misconfiguration will cause Fluentd to malfunction.
                    type: string
                  fluentdTlsVersion:
                    description: |
                      This property specifies the TLS version for Fluentd. See the Fluentd documentation for more information https://docs.fluentd.org/configuration/transport-section#tls-setting
                      If you want to accept multiple TLS protocols, use fluentdTlsMinVersion and fluentdTlsMaxVersion instead of fluentdTlsVersion.
                    type: string
                    enum: ["TLSv1_1", "TLS1_2", "TLS1_3"]
                  fluentdTlsMinVersion:
                    description: |
                      This property specifies the minimal TLS version for Fluentd. See the Fluentd documentation for more information https://docs.fluentd.org/configuration/transport-section#tls-setting
                      If fluentdTlsMinVersion is set, fluentdTlsMaxVersion must also be set.
                    type: string
                    enum: ["TLSv1_1", "TLS1_2", "TLS1_3"]
                  fluentdTlsMaxVersion:
                    description: |
                      This property specifies the maximal TLS version for Fluentd. See the Fluentd documentation for more information https://docs.fluentd.org/configuration/transport-section#tls-setting
                      If fluentdTlsMaxVersion is set, fluentdTlsMinVersion must also be set.
                    type: string
                    enum: ["TLSv1_1", "TLS1_2", "TLS1_3"]
                  groks:
                    description: |
                      It is possible to define additional grok patterns, which will be matched against the message part of the syslog. As soon the first grok pattern will match, the next will not apply to it.
                      If you want to remove all additional groks just apply the custom parameter with an empty array.
                      See the documentation for more information https://docs.anynines.com/docs/application-developer/a9s-logme2/a9s-ad-logme2-custom-parameters#groks
                    type: array
                    items:
                      type: object
                      required:
                        - pattern
                      properties:
                        pattern:
                          type: string
            required:
              - service
              - plan
          status:
            type: object
            properties:
              managed:
                type: object
                x-kubernetes-preserve-unknown-fields: true
    additionalPrinterColumns:
    - name: ManagedResource
      type: string
      jsonPath: ".status.managed.state"
