name: Create Release
run-name: "Create Release from #${{ github.event.pull_request.number }} - ${{ github.event.pull_request.title }}"

on:
  pull_request:
    types: [closed]
    branches:
      - main*

jobs:
  create-release:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'release')
    steps:
      - name: Parse PR Body
        id: parse-pr-body
        run: |
          VERSION_NUMBER=$(echo "${{ github.event.pull_request.body }}" | grep -E '^\[version-number: [^]]+\]::$' | sed 's/\[version-number: //;s/\]:://')
          if [[ -z "$VERSION_NUMBER" ]]; then
            echo "Error: Version number not found in PR body."
            exit 1
          fi
          RUN_ID=$(echo "${{ github.event.pull_request.body }}" | grep -E '^\[run-id: [^]]+\]::$' | sed 's/\[run-id: //;s/\]:://')
          if [[ -z "$RUN_ID" ]]; then
            echo "Error: RunID not found in PR body."
            exit 1
          fi
          (
            echo "version-number=$VERSION_NUMBER"
            echo "run-id=$RUN_ID"
          ) >> $GITHUB_OUTPUT

      - name: Download all binaries
        uses: actions/download-artifact@v4
        with:
          pattern: klutch-bind-*
          merge-multiple: true
          path: binaries/
          run-id: ${{ steps.parse-pr-body.outputs.run-id }}
          github-token: ${{ github.token }}
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          target_commitish: ${{ github.event.pull_request.head.sha }}
          tag_name: ${{ steps.parse-pr-body.outputs.version-number }}
          name: ${{ steps.parse-pr-body.outputs.version-number }}
          token: ${{ github.token }}
          generate_release_notes: true
          files: binaries/*
      - name: Delete binary artifacts
        run: |
          ENDPOINT="$(printf '/repos/%s/actions/runs/%s/artifacts' \
            "${{ github.repository }}" \
            "${{ steps.parse-pr-body.outputs.run-id }}"
          )"
          gh api -X DELETE -H "Accept: application/vnd.github+json" "$ENDPOINT"
