name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version number (e.g. v1.2.3)"
        required: true
        type: string

env:
  ECR_REGISTRY_ADDRESS: "public.ecr.aws/w5n9a2g2"
  VERSION_NR: ${{ inputs.version }}
  SEMVER_EXP: 'v[0-9]\.[0-9]\.[0-9](-[-.A-z0-9]+)?'

jobs:
  create-branch:
    name: Create Branch for Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Check Version Number Format
        run: |
          if ! echo "$VERSION_NR" | grep -E "^$SEMVER_EXP"'$' -q; then
              echo "illegal version number $VERSION_NR.\n\n" \
                  "Please use a version number that matches this regular" \
                  "expression: $SEMVER_EXP"
              exit 1
          fi
      - name: Checkout klutchio
        uses: actions/checkout@v6
        with:
          ref: "main"
          fetch-depth: 0
          token: ${{ github.token }}
      - name: Create release branch
        run: |
          git checkout -b "releases/${{ inputs.version }}"
          git push -u origin "releases/${{ inputs.version }}"
  create-konnector-images:
    name: Build and Push Konnector Images
    needs: create-branch
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout klutchio
        uses: actions/checkout@v6
        with:
          ref: releases/${{ inputs.version }}
          fetch-depth: 0
          token: ${{ github.token }}
      - name: Setup
        uses: ./.github/actions/release-setup
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          github-token: ${{ github.token }}
      - name: Build and push images
        env:
          GITHUB_TOKEN: ${{ github.token }}
          KOCACHE: /tmp/ko
        run: |
          aws ecr-public get-login-password --region us-east-1 | \
              docker login --username AWS \
              --password-stdin "${ECR_REGISTRY_ADDRESS}"

          cd "bind"

          KO_DOCKER_REPO="${ECR_REGISTRY_ADDRESS}/klutch/konnector" ko build \
              "./cmd/konnector" --bare -t "${VERSION_NR}" \
              --platform=linux/amd64,linux/arm64
  create-example-backend-images:
    name: Build and Push Example Backend Images
    needs: create-branch
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout klutchio
        uses: actions/checkout@v6
        with:
          ref: releases/${{ inputs.version }}
          fetch-depth: 0
          token: ${{ github.token }}
      - name: Setup
        uses: ./.github/actions/release-setup
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          github-token: ${{ github.token }}
      - name: Build and push images
        env:
          GITHUB_TOKEN: ${{ github.token }}
          KOCACHE: /tmp/ko
        run: |
          aws ecr-public get-login-password --region us-east-1 | \
              docker login --username AWS \
              --password-stdin "${ECR_REGISTRY_ADDRESS}"

          cd "bind"

          KO_DOCKER_REPO="${ECR_REGISTRY_ADDRESS}/klutch/example-backend" ko build \
              "./cmd/example-backend" --bare -t "${VERSION_NR}" \
              --platform=linux/amd64,linux/arm64
  create-provider-anynines-controller-images:
    name: Build and Push Provider anynines Controller Images
    needs: create-branch
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout klutchio
        uses: actions/checkout@v6
        with:
          ref: releases/${{ inputs.version }}
          fetch-depth: 0
          token: ${{ github.token }}
      - name: Setup
        uses: ./.github/actions/release-setup
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          github-token: ${{ github.token }}
      - name: Build and push images
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          aws ecr-public get-login-password --region us-east-1 | \
          docker login --username AWS \
          --password-stdin "${ECR_REGISTRY_ADDRESS}"

          cd "provider-anynines"
          git submodule update --init --recursive
          make buildx.all IMAGETAG="${VERSION_NR}"
  create-provider-anynines-image:
    name: Build and Push Provider anynines Image
    needs: create-branch
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout klutchio
        uses: actions/checkout@v6
        with:
          ref: releases/${{ inputs.version }}
          fetch-depth: 0
          token: ${{ github.token }}
      - name: Setup
        uses: ./.github/actions/release-setup
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          github-token: ${{ github.token }}
      - name: Build and push images
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          aws ecr-public get-login-password --region us-east-1 | \
              docker login --username AWS \
              --password-stdin "${ECR_REGISTRY_ADDRESS}"

          cd "provider-anynines"
          git submodule update --init --recursive
          make provider-build-push IMAGETAG="${VERSION_NR}"
  create-dataservices-config-package:
    name: Build and Push Dataservices Config Package
    needs: create-branch
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout klutchio
        uses: actions/checkout@v6
        with:
          ref: releases/${{ inputs.version }}
          fetch-depth: 0
          token: ${{ github.token }}
      - name: Setup
        uses: ./.github/actions/release-setup
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          github-token: ${{ github.token }}
      - name: Build and push images
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |

          aws ecr-public get-login-password --region us-east-1 | \
              docker login --username AWS \
              --password-stdin "${ECR_REGISTRY_ADDRESS}"

          make -C crossplane-api dataservices-config-push \
              dataservicesConfigVersion="${VERSION_NR}"
  create-klutch-bind-binaries:
    name: Build and Push Klutch-Bind Binaries
    needs: create-branch
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: ["linux", "darwin", "windows"]
        goarch: ["amd64", "arm64", "386"]
        exclude:
          - goos: darwin
            goarch: "386"
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout klutchio
        uses: actions/checkout@v6
        with:
          ref: releases/${{ inputs.version }}
          fetch-depth: 0
          token: ${{ github.token }}
      - name: Setup
        uses: ./.github/actions/release-setup
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          github-token: ${{ github.token }}
      - name: Build and push images
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          cd "bind"
          GOOS="$GOOS" GOARCH="$GOARCH" go build -o bin/ ./cmd/kubectl-bind
          if [[ "$GOOS" == "windows" ]]; then
              mv "./bin/kubectl-bind.exe" "../klutch-bind-$GOOS-$GOARCH.exe"
          else
              mv "./bin/kubectl-bind" "../klutch-bind-$GOOS-$GOARCH"
          fi
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: klutch-bind-${{ matrix.goos }}-${{ matrix.goarch }}
          path: ./klutch-bind-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.goos == 'windows' && '.exe' || '' }}
  update-version-refs:
    name: Update Manifests
    needs:
    - create-konnector-images
    - create-example-backend-images
    - create-provider-anynines-controller-images
    - create-provider-anynines-image
    - create-dataservices-config-package
    - create-klutch-bind-binaries
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout klutchio
        uses: actions/checkout@v6
        with:
          ref: releases/${{ inputs.version }}
          fetch-depth: 0
          token: ${{ github.token }}
      - name: Setup
        uses: ./.github/actions/release-setup
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          github-token: ${{ github.token }}
      - name: Update manifests with new image tags
        env:
          GITHUB_TOKEN: ${{ github.token }}
          CROSSPLANE_API_SUBFOLDER: "crossplane-api"
          PROVIDER_ANYNINES_SUBFOLDER: "provider-anynines"
          E2E_TESTS_SUBFOLDER: "test/e2e"
          KON_REPO: "klutch/dataservices"
          README_PATH: "crossplane-api/README.md"
          BUNDLE_IMAGE: "${{ env.ECR_REGISTRY_ADDRESS }}/klutch/dataservices:${{ env.VERSION_NR }}"
          PROVIDER_IMAGE: "${{ env.ECR_REGISTRY_ADDRESS }}/klutch/provider-anynines:${{ env.VERSION_NR }}"
        run: |
          yq -i ".spec.package = \"$BUNDLE_IMAGE\"" \
              "$CROSSPLANE_API_SUBFOLDER/deploy/config-pkg-anynines.yaml"
          yq -i \
              "with(select(document_index == 0); .spec.package=\"$PROVIDER_IMAGE\")" \
              "$CROSSPLANE_API_SUBFOLDER/deploy/provider-anynines.yaml"

          sed -E 's|'"$KON_REPO:$SEMVER_EXP"'|'"$KON_REPO:${VERSION_NR}"'|g' \
              "$README_PATH" >"${README_PATH}.tmp"
          mv "${README_PATH}.tmp" "$README_PATH"

          yq -i ".spec.package = \"$PROVIDER_IMAGE\"" \
              "$PROVIDER_ANYNINES_SUBFOLDER/examples/provider/provider.yaml"
          yq -i ".spec.package = \"$PROVIDER_IMAGE\"" \
              "$E2E_TESTS_SUBFOLDER/provider/manifests/install/provider.yaml"
          yq -i ".spec.package = \"$BUNDLE_IMAGE\"" \
              "$E2E_TESTS_SUBFOLDER/provider/manifests/configuration.yaml"
      - name: Update ChangeLog
        run: |
            HEADLINE="[${VERSION_NR:1}] - $(date "+%Y-%m-%d")"
            if grep -x -q -F "## $HEADLINE" "./CHANGELOG.md"; then
                echo "Changelog already contains a section for version" \
                    "$VERSION_NR. Skipping..."
                exit 0
            fi

            echo "Replacing 'Unreleased' changelog section header with" \
                "header '$HEADLINE'..."
            sed -E 's/^## Unreleased$/'"## $HEADLINE/g" \
                "./CHANGELOG.md" >"./CHANGELOG.md.tmp"
            mv "./CHANGELOG.md.tmp" "./CHANGELOG.md"
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Prepare ${{ inputs.version }} Release" || echo "No changes to commit"
          git push
  create-release:
    name: Create GitHub Release
    needs: [update-version-refs]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Merge release
        uses: devmasx/merge-branch@1.4.0
        with:
          type: now
          from_branch: releases/${{ inputs.version }}
          target_branch: main
          github_token: ${{ github.token }}
          message: "Release ${{ inputs.version }}"
      - name: Checkout Main Branch
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Download all binaries
        uses: actions/download-artifact@v4
        with:
          pattern: klutch-bind-*
          merge-multiple: true
          path: binaries/
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.version }}
          name: ${{ inputs.version }}
          files: binaries/*
          token: ${{ github.token }}
