name: Trigger klutchio-website build on docs change
on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'

jobs:
  send-event:
    runs-on: ubuntu-latest
    steps:
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v3
      with:
        token: ${{ secrets.PAT }}
        repository: anynines/klutchio-website
        event-type: klutch-docs-updated-on-main